server:
  port: 8088

spring:
  thymeleaf:
    cache: false
  application:
    name: team-manager
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    name: cashier-datasource-mysql
    url: jdbc:mariadb://127.0.0.1:3306/team-manager?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 19860717Xst
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.mariadb.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxOpenPreparedStatements: 20



mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.jonda.team.repository.entity

